### PR TITLE
Adding minified file for validate.js

### PR DESCRIPTION
**Pull request by abishekrsrikaanth**
Adding minified file for validate.js

### CODE REVIEW

**Comment by abishekrsrikaanth** [comment]
@rickharrison Will you be doing a new release with the minified file?

**Comment by rickharrison** [comment]
What do you mean by new release? Do you need me to push to npm? I thought this was for some sort of npm competitor.

**Comment by megawac** [comment]
Hi @rickharrison, it's not an npm competitor per-se; it's just a file host. The auto update works by detecting new git tags (or npm/bower versions) and adding the select files to the CDN. As the minified file was not included on the last tag it won't be detected by the auto update bot.

If you could do a github release/ `git tag v1.4.1` it'll be picked up

**Comment by megawac** [comment]
It looks like you're missing some git tags anyway (`v1.5`)

**Comment by rickharrison** [comment]
ok that should be good

**Pull request merged**
