### PR TITLE
Added a return false to the _validateForm function if there are any errors

### PR DESCRIPTION
**Pull request by mikegioia**
This is a very small one-liner but I needed it for my application since I have to call _validateForm directly. It would also be nice if there was a way to run that with a more public feel to it as I think I'm using an internal method :P

### CODE REVIEW

**Comment by rickharrison** [comment]
What do you need to return false for? There are already calls to stop propagation.

**Comment by rickharrison** [comment]
Why do you need to return false? There is already code there to stop propagation.

**Comment by mikegioia** [comment]
I'm not using the onSubmit or event at all. Basically, I'm calling:
```
var validator = new FormValidator( ... );
return validator._validateForm();
```
I need that `_validateForm()` to return true or false depending on whether the form was validated. Currently it returns true regardless of any errors.

**Comment by rickharrison** [comment]
I unfortunately cannot change the behavior of the library for this use case. I'd be more than happy to help you figure out how to accomplish your end goal given the state of the library, whether that is stopping the event or some other purpose.

**Comment by mikegioia** [comment]
That's ok. It seems odd to me that _validateForm() would ever return true when it fails to validate though, regardless of what events are being prevented. But I'll just fork the repo and use it that way.

**Comment by rickharrison** [comment]
returning false is an incorrect way to stop event propagation. It calls `stopPropgation` or sets `returnValue` for IE.

**Comment by mikegioia** [comment]
I'm not using the event at all in this case. I'm merely running the validator and asking _validateForm() to tell me if the form was valid or not.

**Comment by rickharrison** [comment]
I understand that. But the other 99% of people who use this library use it as part of the `onSubmit` handler where return false would be incorrect.

**Comment by rickharrison** [comment]
You can check if FormValidator has `errors`

**Comment by mikegioia** [comment]
Ok, that's fine. It's unclear to me, though, how adding this `return false` breaks the existing behavior, unless you mean the `_onsubmit` on line 126 will never fire here:
```
try {
    return that._validateForm(evt) && (_onsubmit === undefined || _onsubmit());
} catch(e) {}
```
If that's the case, it seems like you could just call _onsubmit() before the return statement. But regardless, I'll probably end up adding more stuff later so it'll be easier to fork it.

**Pull request closed without merging**
